name: Build Android APK

on:
  push:
    branches: [master]

jobs:
  build-frontend:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: cd frontend && npm install
        env:
          CI: ""
      - name: Make gradlew executable
        run: cd frontend/android && chmod +x ./gradlew
      - name: Build Android Release APK
        run: cd frontend && npm run build-release
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: frontend/android/app/build/outputs/apk/release/
