# Deploying a back-end server with a process manager configured(pm2)
name: EC2 deployment

on:
  push:
    branches: [master]

jobs:
build-backend:
  runs-on: ubuntu-16.04
  steps:
    - uses: actions/checkout@master
    - name: setup
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: copy
      uses: appleboy/scp-action@master
      with:
        host: "ip-here"
        username: "ubuntu"
        source: "backend"
        target: "/home/ubuntu"
        key: ${{secrets.SSH_DEPLOYMENT_KEY}}
    - name: restart
      uses: appleboy/ssh-action@master
      with:
        key: ${{secrets.SSH_DEPLOYMENT_KEY}}
        host: "ip-here"
        username: "ubuntu"
        script: |
          cd backend
          sudo npm ci
          sudo pm2 stop all
          sudo pm2 start npm -- start
